/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DetectedEvent {
  'instrument' : string,
  'time' : bigint,
  'soundType' : string,
  'intensity' : number,
}
export interface InstrumentPreset {
  'name' : string,
  'mappings' : Array<SoundMapping>,
}
export interface InstrumentalProject {
  'bpm' : bigint,
  'name' : string,
  'events' : Array<DetectedEvent>,
  'timestamp' : Time,
  'mappings' : Array<SoundMapping>,
}
export interface ProjectWithId {
  'id' : bigint,
  'project' : InstrumentalProject,
}
export interface SessionRecord {
  'melodyCount' : bigint,
  'kickCount' : bigint,
  'snareCount' : bigint,
  'timestamp' : Time,
  'hihatCount' : bigint,
  'bassCount' : bigint,
}
export interface SoundMapping { 'instrument' : string, 'mouthSound' : string }
export type Time = bigint;
export interface _SERVICE {
  'addSessionRecord' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint],
    undefined
  >,
  'createPreset' : ActorMethod<[string, Array<SoundMapping>], undefined>,
  'createProject' : ActorMethod<
    [string, bigint, Array<SoundMapping>, Array<DetectedEvent>],
    bigint
  >,
  'deletePreset' : ActorMethod<[string], undefined>,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'getAllPresets' : ActorMethod<[], Array<InstrumentPreset>>,
  'getAllProjects' : ActorMethod<[], Array<ProjectWithId>>,
  'getAllSessionRecords' : ActorMethod<[], Array<SessionRecord>>,
  'getPreset' : ActorMethod<[string], [] | [InstrumentPreset]>,
  'getProject' : ActorMethod<[bigint], [] | [InstrumentalProject]>,
  'updatePreset' : ActorMethod<[string, Array<SoundMapping>], undefined>,
  'updateProject' : ActorMethod<
    [bigint, string, bigint, Array<SoundMapping>, Array<DetectedEvent>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];