/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SoundMapping = IDL.Record({
  'instrument' : IDL.Text,
  'mouthSound' : IDL.Text,
});
export const DetectedEvent = IDL.Record({
  'instrument' : IDL.Text,
  'time' : IDL.Nat,
  'soundType' : IDL.Text,
  'intensity' : IDL.Float64,
});
export const InstrumentPreset = IDL.Record({
  'name' : IDL.Text,
  'mappings' : IDL.Vec(SoundMapping),
});
export const Time = IDL.Int;
export const InstrumentalProject = IDL.Record({
  'bpm' : IDL.Nat,
  'name' : IDL.Text,
  'events' : IDL.Vec(DetectedEvent),
  'timestamp' : Time,
  'mappings' : IDL.Vec(SoundMapping),
});
export const ProjectWithId = IDL.Record({
  'id' : IDL.Nat,
  'project' : InstrumentalProject,
});
export const SessionRecord = IDL.Record({
  'melodyCount' : IDL.Nat,
  'kickCount' : IDL.Nat,
  'snareCount' : IDL.Nat,
  'timestamp' : Time,
  'hihatCount' : IDL.Nat,
  'bassCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addSessionRecord' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'createPreset' : IDL.Func([IDL.Text, IDL.Vec(SoundMapping)], [], []),
  'createProject' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Vec(SoundMapping), IDL.Vec(DetectedEvent)],
      [IDL.Nat],
      [],
    ),
  'deletePreset' : IDL.Func([IDL.Text], [], []),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'getAllPresets' : IDL.Func([], [IDL.Vec(InstrumentPreset)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(ProjectWithId)], ['query']),
  'getAllSessionRecords' : IDL.Func([], [IDL.Vec(SessionRecord)], ['query']),
  'getPreset' : IDL.Func([IDL.Text], [IDL.Opt(InstrumentPreset)], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(InstrumentalProject)], ['query']),
  'updatePreset' : IDL.Func([IDL.Text, IDL.Vec(SoundMapping)], [], []),
  'updateProject' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(SoundMapping),
        IDL.Vec(DetectedEvent),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SoundMapping = IDL.Record({
    'instrument' : IDL.Text,
    'mouthSound' : IDL.Text,
  });
  const DetectedEvent = IDL.Record({
    'instrument' : IDL.Text,
    'time' : IDL.Nat,
    'soundType' : IDL.Text,
    'intensity' : IDL.Float64,
  });
  const InstrumentPreset = IDL.Record({
    'name' : IDL.Text,
    'mappings' : IDL.Vec(SoundMapping),
  });
  const Time = IDL.Int;
  const InstrumentalProject = IDL.Record({
    'bpm' : IDL.Nat,
    'name' : IDL.Text,
    'events' : IDL.Vec(DetectedEvent),
    'timestamp' : Time,
    'mappings' : IDL.Vec(SoundMapping),
  });
  const ProjectWithId = IDL.Record({
    'id' : IDL.Nat,
    'project' : InstrumentalProject,
  });
  const SessionRecord = IDL.Record({
    'melodyCount' : IDL.Nat,
    'kickCount' : IDL.Nat,
    'snareCount' : IDL.Nat,
    'timestamp' : Time,
    'hihatCount' : IDL.Nat,
    'bassCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addSessionRecord' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'createPreset' : IDL.Func([IDL.Text, IDL.Vec(SoundMapping)], [], []),
    'createProject' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(SoundMapping), IDL.Vec(DetectedEvent)],
        [IDL.Nat],
        [],
      ),
    'deletePreset' : IDL.Func([IDL.Text], [], []),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'getAllPresets' : IDL.Func([], [IDL.Vec(InstrumentPreset)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(ProjectWithId)], ['query']),
    'getAllSessionRecords' : IDL.Func([], [IDL.Vec(SessionRecord)], ['query']),
    'getPreset' : IDL.Func([IDL.Text], [IDL.Opt(InstrumentPreset)], ['query']),
    'getProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(InstrumentalProject)],
        ['query'],
      ),
    'updatePreset' : IDL.Func([IDL.Text, IDL.Vec(SoundMapping)], [], []),
    'updateProject' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(SoundMapping),
          IDL.Vec(DetectedEvent),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };