/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProjectWithId {
    id: bigint;
    project: InstrumentalProject;
}
export type Time = bigint;
export interface SessionRecord {
    melodyCount: bigint;
    kickCount: bigint;
    snareCount: bigint;
    timestamp: Time;
    hihatCount: bigint;
    bassCount: bigint;
}
export interface InstrumentPreset {
    name: string;
    mappings: Array<SoundMapping>;
}
export interface DetectedEvent {
    instrument: string;
    time: bigint;
    soundType: string;
    intensity: number;
}
export interface SoundMapping {
    instrument: string;
    mouthSound: string;
}
export interface InstrumentalProject {
    bpm: bigint;
    name: string;
    events: Array<DetectedEvent>;
    timestamp: Time;
    mappings: Array<SoundMapping>;
}
export interface backendInterface {
    addSessionRecord(kickCount: bigint, snareCount: bigint, hihatCount: bigint, bassCount: bigint, melodyCount: bigint): Promise<void>;
    createPreset(name: string, mappings: Array<SoundMapping>): Promise<void>;
    createProject(name: string, bpm: bigint, mappings: Array<SoundMapping>, events: Array<DetectedEvent>): Promise<bigint>;
    deletePreset(name: string): Promise<void>;
    deleteProject(id: bigint): Promise<void>;
    getAllPresets(): Promise<Array<InstrumentPreset>>;
    getAllProjects(): Promise<Array<ProjectWithId>>;
    getAllSessionRecords(): Promise<Array<SessionRecord>>;
    getPreset(name: string): Promise<InstrumentPreset | null>;
    getProject(id: bigint): Promise<InstrumentalProject | null>;
    updatePreset(name: string, mappings: Array<SoundMapping>): Promise<void>;
    updateProject(id: bigint, name: string, bpm: bigint, mappings: Array<SoundMapping>, events: Array<DetectedEvent>): Promise<void>;
}
import type { InstrumentPreset as _InstrumentPreset, InstrumentalProject as _InstrumentalProject } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addSessionRecord(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSessionRecord(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSessionRecord(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createPreset(arg0: string, arg1: Array<SoundMapping>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPreset(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPreset(arg0, arg1);
            return result;
        }
    }
    async createProject(arg0: string, arg1: bigint, arg2: Array<SoundMapping>, arg3: Array<DetectedEvent>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deletePreset(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePreset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePreset(arg0);
            return result;
        }
    }
    async deleteProject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async getAllPresets(): Promise<Array<InstrumentPreset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPresets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPresets();
            return result;
        }
    }
    async getAllProjects(): Promise<Array<ProjectWithId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return result;
        }
    }
    async getAllSessionRecords(): Promise<Array<SessionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSessionRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSessionRecords();
            return result;
        }
    }
    async getPreset(arg0: string): Promise<InstrumentPreset | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreset(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreset(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: bigint): Promise<InstrumentalProject | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePreset(arg0: string, arg1: Array<SoundMapping>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePreset(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePreset(arg0, arg1);
            return result;
        }
    }
    async updateProject(arg0: bigint, arg1: string, arg2: bigint, arg3: Array<SoundMapping>, arg4: Array<DetectedEvent>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InstrumentPreset]): InstrumentPreset | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InstrumentalProject]): InstrumentalProject | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
